### ISSUE TITLE
Add `Endpoint` as a resource with no spec for dependent resources

### ISSUE THREAD

**Issue by csviri** [operator-framework/java-operator-sdk#1982]
Reported by used:

```
ERROR ReconciliationDispatcher.java (64) Error during event processing ExecutionScope{ resource id: ResourceID{name='test-resource', namespace='default'}, version: 42334818} failed.
io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
 
com.example.test.PostgresEndpoint -> java.lang.IllegalStateException: No spec found on resource io.fabric8.kubernetes.api.model.Endpoints
  at io.javaoperatorsdk.operator.ReconcilerUtils.noSpecException(ReconcilerUtils.java:146)
  at io.javaoperatorsdk.operator.ReconcilerUtils.getSpec(ReconcilerUtils.java:111)
  at io.javaoperatorsdk.operator.processing.dependent.kubernetes.ResourceUpdatePreProcessor.matches(ResourceUpdatePreProcessor.java:18)...
Caused by: java.lang.NoSuchMethodException: io.fabric8.kubernetes.api.model.Endpoints.getSpec()
    at java.base/java.lang.Class.getMethod(Class.java:2108)
    at io.javaoperatorsdk.operator.ReconcilerUtils.getSpec(ReconcilerUtils.java:108)
    ... 15 more
    
```

**Comment by metacosm** [comment]
We probably need to push for `HasSpec` & `HasStatus` support in the fabric8 client to address these issues once and for all.

**Comment by csviri** [comment]
> We probably need to push for `HasSpec` & `HasStatus` support in the fabric8 client to address these issues once and for all.

totally, comes up again and again, can pick it up after the helm issue

**Comment by metacosm** [comment]
Yes, there's another similar issue in QOSDK and RBAC generation
