### ISSUE TITLE
Orphan secondary resources are left when using annotation based owner reference

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [operator-framework/java-operator-sdk#2259]
#### What did you do?

We have a primary resource, let's call it `MyCustomResource`. The reconciler for this resource creates and maintains a `ConfigMap` based on the `MyCustomResource`. The `ConfigMap` is created in a different namespace than `MyCustomResource`, thus we cannot use the `ownerReference` mechanism to ensure that the resource is deleted when the primary resource is deleted. To do so, we use JOSDK annotations (`primary-name` and `primary-namespace`).

The issue is that sometimes when the primary resource is deleted very quickly - right after it was created, the secondary resource is not created:

```
2024-03-04 10:12:17,918 ERROR [io.jav.ope.pro.eve.EventProcessor] (ReconcilerExecutor-mycustomresourcereconciler-117) Error during event processing ExecutionScope{ resource id: ResourceID{name='test', namespace='default'}, version: 7364248}: java.lang.NullPointerException: Cannot invoke "io.fabric8.kubernetes.api.model.HasMetadata.addFinalizer(String)" because "r" is null
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.lambda$updateCustomResourceWithFinalizer$2(ReconciliationDispatcher.java:331)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.conflictRetryingUpdate(ReconciliationDispatcher.java:353)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.updateCustomResourceWithFinalizer(ReconciliationDispatcher.java:330)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:116)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:90)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:450)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

So it seems that the secondary resource is created, even though the primary resource has no finalizer added.

This issue was reproduced with a [sample repo](https://github.com/AleksanderBrzozowski/josdk-race-condition/blob/main/src/test/kotlin/MyResourceReconcilerTest.kt). There is a repeated test that fails after several test loops - it is non deterministic.

#### What did you expect to see?

There are no Orphan secondary resources left, when the Primary is deleted.

#### What did you see instead? Under which circumstances?

There is an Orphan secondary resource left, that will be never deleted.

#### Environment

**Kubernetes cluster type:**

rancher desktop, version: 1.25

`$ Mention java-operator-sdk version from pom.xml file`

`4.8.0`

`$ java -version`

`Java Temurin 17.0.6`

`$ kubectl version`

kubectl version doesn't seem to be related, under the hood JOSDK is using fabric8 kubernetes client with version `6.10.0`

#### Possible Solution

Make sure that the finalizer is applied first before creating secondary resources

**Comment by csviri** [comment]
This is the code part:

https://github.com/operator-framework/java-operator-sdk/blob/6d24455a4ee181cb1994cc4a89d4cf08fcdcc34c/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java#L104-L125

**Comment by AleksanderBrzozowski** [comment]
Yeah, I saw this code part. But it seems that in some cases it doesn't work correctly. Have you tried running the test from my sample repo? 🙂

**Comment by csviri** [comment]
Notes: tried to reproduce, it seems that the reconciler is not called when it fails in my case.

**Comment by AleksanderBrzozowski** [comment]
Not sure that I follow 😛 

So I guess that you were able to reproduce the test?

Are you saying that we can somehow fix this issue by modifying the code? The `ConfigMapDependentResource` already extends `KubernetesDependentResource` class 🙂

**Comment by csviri** [comment]
> Are you saying that we can somehow fix this issue by modifying the code? The ConfigMapDependentResource already extends KubernetesDependentResource class 🙂

No, not saying that :)   still investigating, will probably take a while

**Comment by AleksanderBrzozowski** [comment]
No need to rush. We don't have this problem in production, we only discovered it when running integration tests, and we were able to solve it 🙂

**Comment by csviri** [comment]
interesting is that I created a reproducer now in pure Java and not using Quarkus and not able to reproduce there:
https://github.com/csviri/race-condition-reproducer

**Comment by csviri** [comment]
The problem seems to be with either k8s API or informer:

```
2024-03-04 14:32:33,843 DEBUG [io.jav.ope.pro.eve.sou.con.ControllerResourceEventSource] (-1660409789-pool-11-thread-3) Event received for resource: ResourceID{name='test', namespace='default'} version: 3156 uuid: cd21c403-f3e4-4830-8efe-a597f77155c1 action: DELETED
2024-03-04 14:32:33,843 DEBUG [io.jav.ope.pro.eve.sou.con.ControllerResourceEventSource] (-1660409789-pool-11-thread-3) Event Old resource: null,
 new resource: CustomResource{kind='MyCustomResource', apiVersion='example.com/v1alpha1', metadata=ObjectMeta(annotations={}, creationTimestamp=2024-03-04T13:32:33Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[mycustomresources.example.com/finalizer], generateName=null, generation=1, labels={}, managedFields=[], name=test, namespace=default, ownerReferences=[], resourceVersion=3156, selfLink=null, uid=cd21c403-f3e4-4830-8efe-a597f77155c1, additionalProperties={}), spec=null, status=null}
2024-03-04 14:32:33,843 DEBUG [io.jav.ope.pro.eve.EventProcessor] (-1660409789-pool-11-thread-3) Received event: ResourceEvent{action=DELETED, associated resource id=ResourceID{name='test', namespace='default'}}
```
As can be seen here we receive a delete event for a resource that still has a finalizer.

cc @shawkins @manusa @metacosm

**Comment by csviri** [comment]
Why the test case fails:
1. we receive an update event after the finalizer added to the resource
2. the reconciliation process starts
3. meanwhile a Delete event received (for a resource with a finalizer 😱) 
4. `Delete events`  has special meaning, it cleans up all kind of caches. So the cleaner part not even executed.

**Comment by shawkins** [comment]
> meanwhile a Delete event received (for a resource with a finalizer 😱)

Just to make sure, are there any labels or other filters that the informer is based off of? If that's the case you will see a delete event when any of that no longer matches, not just when the resource no longer exists.

**Comment by csviri** [comment]
No there are no labels involved. 
This seems to be a race condition with the API server. If I add in a test waiting while the finalizer is actually added and just then call the delete, it does not fail:

```java
  client.resource(resource).create()

        await().untilAsserted{
          val res = client.resources(MyCustomResource::class.java)
                    .inNamespace("default")
                    .withName("test")
                    .get();
            assertEquals(res.metadata.finalizers.size,1)
        }
        Thread.sleep(5)


        // delete the primary, and wait until it is deleted
        client.resources(MyCustomResource::class.java)
            .inNamespace("default")
            .withName("test")
            .withTimeout(5, TimeUnit.SECONDS)
            .delete()
```

**Comment by csviri** [comment]
Btw AFAIK `Thread.sleep(5)` maybe yields but does not wait 5ms - in general sleep under 15ms does not work.

**Comment by csviri** [comment]
asked also for clarification on k8s slack: https://kubernetes.slack.com/archives/C0EG7JC6T/p1709561696968339
