### ISSUE TITLE
Sample GettingStarted project Error within IT 

### ISSUE THREAD

**Issue by Malek-Zaag** [operator-framework/java-operator-sdk#2439]
## Bug Report

Hi ! I wanted to just run the gettingStarted Sample project Integration test with a little bit of changes to CR. 

#### What did you do?

I ran `mvn verify` to run all the tests (some experiment UT) and the IT provided with the sample.

#### What did you expect to see?

I expected to see the tests passing.

#### What did you see instead? Under which circumstances?

I got the following error : 
```bash
2024-06-15 21:06:14,375 23 i.j.o.p.Controller             [INFO ] 'gettingstartedreconciler' controller started
2024-06-15 21:06:14,763 33 i.j.o.p.e.EventProcessor       [ERROR] Error during event processing ExecutionScope{ resource id: ResourceID{name='test1', namespace='gettingstartedreconcilerit-testcrudoperations-251f9'}, version: 137091}
io.javaoperatorsdk.operator.AggregatedOperatorException: Exception(s) during workflow execution. Details:
 - org.acme.ConfigMapDependentResource -> java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at java.base/java.util.ImmutableCollections$Map1.<init>(ImmutableCollections.java:749)
        at java.base/java.util.Map.of(Map.java:1307)
        at org.acme.ConfigMapDependentResource.desired(ConfigMapDependentResource.java:34)
        at org.acme.ConfigMapDependentResource.desired(ConfigMapDependentResource.java:13)
        at io.javaoperatorsdk.operator.processing.dependent.AbstractDependentResource.reconcile(AbstractDependentResource.java:59)
        at io.javaoperatorsdk.operator.processing.dependent.SingleDependentResourceReconciler.reconcile(SingleDependentResourceReconciler.java:19)
        at io.javaoperatorsdk.operator.processing.dependent.AbstractDependentResource.reconcile(AbstractDependentResource.java:52)
        at io.javaoperatorsdk.operator.processing.dependent.workflow.WorkflowReconcileExecutor$NodeReconcileExecutor.doRun(WorkflowReconcileExecutor.java:123)
        at io.javaoperatorsdk.operator.processing.dependent.workflow.NodeExecutor.run(NodeExecutor.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
#### Environment

kind version 0.22.0

JO version: 4.9.1

java version: 11

kubectl version: v1.29.1

#### Possible Solution

No idea  :(

**Comment by Malek-Zaag** [comment]
Hi @csviri, here is my `desired` function : 
```java 
protected ConfigMap desired(GettingStartedCustomResource primary,
            Context<GettingStartedCustomResource> context) {
        return new ConfigMapBuilder()
                .withMetadata(
                        new ObjectMetaBuilder()
                                .withName(primary.getMetadata().getName())
                                .withNamespace(primary.getMetadata().getNamespace())
                                .build())
                .withData(Map.of(KEY, primary.getSpec().getKey1()))
                .addToData(Map.of(KEY2, primary.getSpec().getKey2()))
                .build();
    }
```
Actually I got it ! 
In my test I needed to instantiate the CR with both keys containing values (I was only adding key1) or the test will result in NPE.

```java
    GettingStartedCustomResource testResource() {
        var resource = new GettingStartedCustomResource();
        resource.setMetadata(new ObjectMetaBuilder()
                .withName(RESOURCE_NAME)
                .build());
        resource.setSpec(new GettingStartedSpec());
        resource.getSpec().setKey1(INITIAL_VALUE);
        resource.getSpec().setKey2(INITIAL_VALUE);
        return resource;
    }
```
Thanks @csviri for your time :)
